# start with a small linux base image with Node.js version 18
FROM node:18-alpine

# set the working directory inside the container
WORKDIR /app
# Add this line to declare the build argument
ARG VITE_MAPBOX_ACCESS_TOKEN

# Add this line to set it as an environment variable for the build
ENV VITE_MAPBOX_ACCESS_TOKEN=$VITE_MAPBOX_ACCESS_TOKEN
# copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# copy the rest of the application code into the container
COPY . .

# expose port 3000 
EXPOSE 3000

# Define the command to run when the container starts
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]