version: '3.8'

services:
  database:
    build: ./database
    container_name: database-container
    environment:
      - POSTGRES_DB=realestate_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    volumes:
     - ./database/database-data:/var/lib/postgresql/data
    networks:
      - app-network
    

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      - ./frontend/package.json:/app/package.json
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    environment:
      - SCRAPER_SERVICE_URL=http://scraper:9000
      - PREDICTOR_SERVICE_URL=http://predictor:8001
      - ENVIRONMENT=dev
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=realestate_db
      - DB_USER=dev_user
      - DB_PASSWORD=dev_password
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  scraper:
    build: ./scraping2
    container_name: scraper-container
    command: uvicorn server:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - ./scraping2:/app
    working_dir: /app
    networks:
      - app-network

  predictor:
    build:
      context: .
      dockerfile: predictor/Dockerfile
    container_name: predictor-container
    command: uvicorn api:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./predictor:/app
      - ./automltrainer:/app/automltrainer_lib
    working_dir: /app
    networks:
      - app-network
    environment:
      - PYTHONPATH=/app/automltrainer_lib/code

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: