version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend-container
    environment:
      - REACT_APP_API_URL=/api  # Frontend uses gateway, not direct backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend-container
    environment:
      - SCRAPER_SERVICE_URL=http://scraper:9000
      - PREDICTOR_SERVICE_URL=http://predictor:8001
    networks:
      - app-network

  api-gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - "80:80"  # Only gateway is exposed
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  scraper:
    build: ./scraping2
    container_name: scraper-container
    networks:
      - app-network

  predictor:
    build:
      context: .
      dockerfile: predictor/Dockerfile
    container_name: predictor-container
    ports:
      - "8001:8001"  # Add this line to expose the port
    networks:
      - app-network
    environment:
      # This is the crucial line that fixes the ModuleNotFoundError
      - PYTHONPATH=/app/automltrainer_lib
    

networks:
  app-network:
    driver: bridge